import { DayTemplate, Phase } from '../types'

export const WARMUP = [
  { name: 'Cat-Camel 8 cycles' },
  { name: 'McGill Big 3 : curl-up + planche laterale + bird dog (pyramide 5-3-1, holds 8 sec)' },
  { name: 'Mobilite hanches 90/90 + psoas stretch (2x8/cote)' },
]

export const PHASES: { id: Phase; title: string; goal: string; duration: string }[] = [
  { id: 1, title: 'Phase 1', goal: '2 → 8 tractions', duration: '6-12 sem.' },
  { id: 2, title: 'Phase 2', goal: '8 tractions → 5 chest-to-bar', duration: '6-10 sem.' },
  { id: 3, title: 'Phase 3', goal: '5 C2B → 1er muscle-up', duration: '4-8 sem.' },
]

export const PROGRAM: DayTemplate[] = [
  {
    id: 'A',
    name: 'Jour A',
    label: 'Tirage',
    duration: '~50 min',
    color: '#2dd4bf',
    exercises: [
      {
        name: 'Tractions strictes (pronation)',
        sets: 5,
        reps: 'max-1',
        load: 'PDC',
        rest: 180,
        tip: 'Partez bras tendus, montez menton au-dessus de la barre. Tempo controle.',
      },
      {
        name: 'Lat Pulldown (pronation, vers sternum)',
        sets: 4,
        reps: '6-8',
        load: 'Lourd RPE 8',
        rest: 150,
        tip: 'Tirez vers le sternum, pas le menton. Serrez les omoplates en bas.',
      },
      {
        name: 'Rowing poitrine appuyee',
        sets: 3,
        reps: '8-10',
        load: 'Modere-lourd',
        rest: 120,
        tip: 'Poitrine collee au support. Tirez les coudes en arriere.',
      },
      {
        name: 'Curl marteau',
        sets: 3,
        reps: '10-12',
        load: 'Modere',
        rest: 60,
        tip: 'Pas de balancement. Controle la descente.',
      },
    ],
  },
  {
    id: 'B',
    name: 'Jour B',
    label: 'Poussee + Jambes',
    duration: '~55 min',
    color: '#f472b6',
    exercises: [
      {
        name: 'Dips barres paralleles',
        sets: 4,
        reps: '6-8',
        load: 'PDC',
        rest: 150,
        tip: 'Descendez jusqu\'a 90° minimum. Gardez les coudes pres du corps.',
      },
      {
        name: 'Extensions triceps overhead (poulie)',
        sets: 3,
        reps: '10-12',
        load: 'Modere',
        rest: 90,
        tip: 'Gardez les coudes fixes, etirez bien en bas.',
      },
      {
        name: 'Belt Squat / Hack Squat machine',
        sets: 4,
        reps: '8-10',
        load: 'Lourd RPE 7-8',
        rest: 150,
        tip: 'Descendez profond. Poussez par les talons.',
      },
      {
        name: 'Bulgarian Split Squat (halteres)',
        sets: 3,
        reps: '8-10/jambe',
        load: 'Modere',
        rest: 90,
        tip: 'Genou avant ne depasse pas les orteils. Gardez le buste droit.',
      },
    ],
  },
  {
    id: 'C',
    name: 'Jour C',
    label: 'Tirage Explosif',
    duration: '~50 min',
    color: '#fbbf24',
    exercises: [
      {
        name: 'Tractions explosives',
        sets: 5,
        reps: '2-3',
        load: 'PDC',
        rest: 180,
        tip: 'Tirez le plus vite possible. Lachez la barre en haut si possible.',
      },
      {
        name: 'Suspensions fausse prise → tractions fausse prise',
        sets: 3,
        reps: '15-25 sec (ou 3x3)',
        load: 'PDC',
        rest: 120,
        tip: 'Poignets par-dessus la barre. Commencez par les suspensions statiques.',
      },
      {
        name: 'Muscle-up negatifs',
        sets: 4,
        reps: '1-2',
        load: 'PDC',
        rest: 180,
        tip: 'Montez en saut, descendez le plus lentement possible (5 sec min).',
        minPhase: 3,
      },
      {
        name: 'Lat Pulldown prise neutre',
        sets: 3,
        reps: '8-10',
        load: 'Modere-lourd',
        rest: 120,
        tip: 'Prise neutre (paumes face a face). Tirez vers le sternum.',
      },
      {
        name: 'Hollow body hold',
        sets: 3,
        reps: '20-30 sec',
        load: 'PDC',
        rest: 60,
        tip: 'Bas du dos colle au sol. Bras et jambes tendus.',
      },
    ],
  },
  {
    id: 'D',
    name: 'Jour D',
    label: 'Poussee + Jambes v2',
    duration: '~55 min',
    color: '#f472b6',
    exercises: [
      {
        name: 'Dips barre droite',
        sets: 4,
        reps: '5-8',
        load: 'PDC',
        rest: 150,
        tip: 'Penchez-vous en avant. Descendez lentement, poussez fort.',
      },
      {
        name: 'Developpe militaire halteres assis',
        sets: 3,
        reps: '8-10',
        load: 'Modere',
        rest: 120,
        tip: 'Gardez le dos droit contre le dossier. Pas de cambrure.',
      },
      {
        name: 'Leg Press',
        sets: 4,
        reps: '10-12',
        load: 'Modere-lourd RPE 7',
        rest: 120,
        tip: 'Pieds largeur epaules. Ne verrouillez pas les genoux en haut.',
      },
      {
        name: 'Hip Thrust',
        sets: 3,
        reps: '10-12',
        load: 'Modere-lourd',
        rest: 90,
        tip: 'Serrez fort les fessiers en haut. Pause 1 sec au sommet.',
      },
    ],
  },
]
